# 2차시 강사용 Notebook — 리스트와 딕셔너리

학생용 Notebook과 동일한 흐름이며, 예상 결과와 설명 포인트를 함께 담았습니다.

코드는 강의 자료(`lectures/week02/index.html`)의 코드 블록과 같습니다. 강의에서는 한 블록으로 보여준 코드도 여기서는 결과가 하나씩 보이도록 셀을 나눴고, 각 셀 맨 위에 초보자용 설명 주석을 달았습니다(학생용과 같은 주석).

## 1단계. 리스트 만들기
**설명 포인트**: 1차시의 변수 하나(`pass_count = 32`)와 비교해 "여러 값을 한 번에 담을 수 있다"는 점을 강조.

**진행 방법**: 강의 자료 순서대로 과일 리스트(`fruits`) 세 셀로 리스트와 인덱스의 감을 잡은 뒤 온도 리스트로 넘어간다.

**예상 결과**: `['사과', '바나나', '포도']` → `사과` → `포도` → `[295.4, 298.1, 312.6, 301.0, 296.8]`

### 따라 해보기 — 아주 간단한 리스트
반도체 데이터로 바로 들어가기 전에, 과일 이름 세 개를 담은 가장 단순한 리스트로 감을 잡습니다
(강의 자료 "먼저 아주 간단한 예로 감을 잡자"). 완성된 코드이니 한 셀씩 실행해 결과를 확인해 보세요.

In [1]:
# 과일 이름 3개를 담은 리스트를 만들어 fruits에 저장하고, 리스트 전체를 출력합니다.
# 실행하면 ['사과', '바나나', '포도']가 출력됩니다 — 대괄호와 콤마까지 그대로 보입니다.
# 리스트: 대괄호 [ ] 안에 값을 콤마(,)로 구분해 나열하면 여러 값을 순서대로 한 번에 담을 수 있습니다.
fruits = ["사과", "바나나", "포도"]
print(fruits)

['사과', '바나나', '포도']


In [2]:
# 리스트에서 첫 번째 값을 꺼내 출력합니다.
# 실행하면 사과가 출력됩니다. 첫 번째 값의 순서 번호(인덱스)는 1이 아니라 0입니다.
# 리스트이름[번호]: 대괄호 안에 인덱스를 넣으면 그 위치의 값을 꺼냅니다.
print(fruits[0])    # 첫 번째 값

사과


In [3]:
# 리스트에서 마지막 값을 꺼내 출력합니다.
# 실행하면 포도가 출력됩니다. -1처럼 음수 인덱스는 뒤에서부터 셉니다.
print(fruits[-1])   # 마지막 값

포도


### 반도체 데이터로 — 온도 리스트 만들기
리스트는 글자뿐 아니라 숫자도 같은 방식으로 담을 수 있습니다. 이제 한 설비의 온도 측정값 5개를 리스트에 담습니다.

In [4]:
# 한 설비에서 측정한 온도 값 5개를 리스트로 만들어 temperatures에 저장하고 출력합니다.
# 실행하면 [295.4, 298.1, 312.6, 301.0, 296.8]이 출력됩니다. 숫자도 글자와 같은 방식으로 리스트에 담습니다.
temperatures = [295.4, 298.1, 312.6, 301.0, 296.8]
print(temperatures)

[295.4, 298.1, 312.6, 301.0, 296.8]


## 2단계. 인덱싱으로 값 꺼내기
**어려워할 부분**: 인덱스가 0부터 시작한다는 점. `temperatures[1]`이 '두 번째' 값임을 직접 실행해서 보여준다.

마지막 셀(`temperatures[1]`)이 강의 "가장 흔한 함정" 확인용이다 — 298.1(두 번째 값)이 나오는 것을 보여준다.

**예상 결과**: `295.4` → `312.6` → `296.8` → `298.1`

In [5]:
# temperatures에서 첫 번째 값을 꺼내 출력합니다.
# 실행하면 295.4가 출력됩니다.
print(temperatures[0])    # 첫 번째 값

295.4


In [6]:
# temperatures에서 세 번째 값을 꺼내 출력합니다.
# 실행하면 312.6이 출력됩니다. 인덱스가 0부터 시작하므로 세 번째 값의 인덱스는 3보다 하나 작습니다.
print(temperatures[2])    # 세 번째 값

312.6


In [7]:
# temperatures에서 마지막 값을 꺼내 출력합니다.
# 실행하면 296.8이 출력됩니다. 값이 몇 개인지 몰라도 음수 인덱스로 뒤에서부터 꺼낼 수 있습니다.
print(temperatures[-1])   # 마지막 값(음수 인덱스는 뒤에서부터)

296.8


In [8]:
# [가장 흔한 함정 확인] 인덱스 1은 "첫 번째"가 아니라 "두 번째" 값입니다.
# 실행하면 298.1(두 번째 값)이 출력됩니다 — 첫 번째 값 295.4가 아닌 것을 눈으로 확인해 보세요.
print(temperatures[1])

298.1


## 3단계. 슬라이싱
**시연 방법**: `temperatures[1:3]`과 `temperatures[1:4]`를 나란히 실행해 끝 인덱스가 포함되지 않음을 비교.

**예상 결과**: `[298.1, 312.6]` → `[295.4, 298.1]` → `[312.6, 301.0, 296.8]` → (직접 해보기) `[301.0, 296.8]`

In [9]:
# 슬라이싱으로 두 번째·세 번째 값(298.1, 312.6)만 잘라 출력합니다.
# 실행하면 [298.1, 312.6]이 출력됩니다 — 결과도 리스트라서 대괄호로 감싸여 나옵니다.
# 리스트이름[시작:끝]: 시작 인덱스부터 끝 인덱스 "바로 앞"까지 잘라냅니다. 끝 인덱스 자신은 들어가지 않습니다.
print(temperatures[1:3])   # 인덱스 1~2 (3은 포함 안 됨)

[298.1, 312.6]


In [10]:
# 시작 인덱스를 비워 두면 처음부터 잘라냅니다. 인덱스 0, 1의 값을 출력합니다.
# 실행하면 [295.4, 298.1]이 출력됩니다.
print(temperatures[:2])    # 처음부터 인덱스 1까지

[295.4, 298.1]


In [11]:
# 끝 인덱스를 비워 두면 마지막 값까지 잘라냅니다. 인덱스 2부터 끝까지 출력합니다.
# 실행하면 [312.6, 301.0, 296.8]이 출력됩니다.
print(temperatures[2:])    # 인덱스 2부터 끝까지

[312.6, 301.0, 296.8]


### 직접 해보기 — 음수 인덱스와 슬라이싱 함께 쓰기
강의 자료 「슬라이싱 — 여러 값을 한 번에 잘라내기」 절의 "직접 해보기" 상자를 노트북에서 실행해 봅니다.

In [12]:
# [직접 해보기] 음수 인덱스와 슬라이싱을 함께 쓰면 어떤 값이 나오는지 확인합니다.
# 실행하면 리스트가 출력됩니다 — 원래 temperatures의 어느 부분이 잘려 나왔는지 비교해 보세요.
print(temperatures[-2:])

[301.0, 296.8]


> **참고**
>
> 강의 자료 「슬라이싱 — 여러 값을 한 번에 잘라내기」 절의 "직접 해보기" 상자에 이 셀의 코드가 그대로 적혀 있습니다. 음수 인덱스는 뒤에서부터 세는 번호이고(「인덱싱 — 순서로 값 꺼내기」 절), `[시작:]`처럼 끝 인덱스를 비워 두면 시작 위치부터 마지막 값까지 잘라냅니다.
>
> 정답 해설: 빈칸은 `-2`. `temperatures[-2:]`는 "뒤에서 두 번째 값부터 끝까지"라서 마지막 두 값이 리스트로 나온다. 음수 인덱스와 슬라이싱을 함께 쓰면 리스트 길이를 몰라도 끝부분을 잘라낼 수 있다.
>
> 예상 결과: `[301.0, 296.8]` (4단계 `append()` 전이라 값 5개 기준. `append()` 뒤에 다시 실행하면 `[296.8, 303.2]`)

## 4단계. 길이와 추가

**주의**: `append()` 셀을 두 번 실행하면 303.2가 두 번 들어가 5단계 결과가 달라진다. 강의 체크포인트 "append()는 아무것도 돌려주지 않는다"(`temperatures = temperatures.append(303.2)` 금지)와 함께 짚는다.

**예상 결과**: `5` → `[295.4, 298.1, 312.6, 301.0, 296.8, 303.2]` → `6`

In [13]:
# 리스트에 값이 몇 개 들어 있는지 세어 출력합니다.
# 실행하면 5가 출력됩니다.
# len(리스트): 리스트에 담긴 값의 개수(길이)를 돌려주는 함수입니다.
print(len(temperatures))     # 리스트 길이(값 개수)

5


In [14]:
# 리스트 끝에 새 온도 값 303.2를 추가한 뒤, 리스트 전체를 다시 출력합니다.
# 실행하면 맨 끝에 303.2가 붙은 6개짜리 리스트가 출력됩니다. 이 셀은 한 번만 실행하세요(다시 실행하면 303.2가 또 붙습니다).
# 리스트.append(값): 리스트 끝에 값을 하나 붙입니다. 돌려주는 결과가 없으므로 temperatures = ...처럼 다시 대입하지 않습니다.
temperatures.append(303.2)   # 끝에 새 값 추가
print(temperatures)

[295.4, 298.1, 312.6, 301.0, 296.8, 303.2]


In [15]:
# 값을 하나 추가한 뒤 리스트 길이를 다시 셉니다.
# 실행하면 6이 출력됩니다 — 처음 5개에서 1개 늘었습니다. 7 이상이 나오면 위 셀을 여러 번 실행한 것이니 1단계부터 다시 실행하세요.
print(len(temperatures))

6


## 5단계. 최댓값·최솟값·평균 계산하기
**설명 포인트**: `round()`로 소수점을 정리하고 1차시의 f-string을 복습으로 다시 사용.

**예상 결과**(4단계에서 303.2를 추가한 6개 값 기준): `312.6` → `295.4` → `1807.1` → `평균 온도는 301.2도입니다.` → (직접 해보기) `17.200000000000045` → `온도 범위는 17.2도입니다.` 소수점 아래가 길게 나오는 이유(부동소수 오차)와 `:.1f` 서식으로 정리하는 방법을 함께 짚는다.

In [16]:
# 리스트에서 가장 큰 값을 찾아 출력합니다.
# 실행하면 312.6이 출력됩니다.
# max(리스트) / min(리스트) / sum(리스트): 리스트 전체의 최댓값 / 최솟값 / 합계를 돌려주는 파이썬 내장 함수입니다.
print(max(temperatures))     # 최댓값

312.6


In [17]:
# 리스트에서 가장 작은 값을 찾아 출력합니다.
# 실행하면 295.4가 출력됩니다.
print(min(temperatures))     # 최솟값

295.4


In [18]:
# 리스트의 모든 값을 더한 합계를 출력합니다.
# 실행하면 1807.1이 출력됩니다(4단계에서 추가한 303.2까지 6개 값의 합).
print(sum(temperatures))     # 합계

1807.1


In [19]:
# 평균(합계 ÷ 개수)을 계산해 average에 저장하고, 소수 첫째 자리까지 반올림해 문장으로 출력합니다.
# 실행하면 "평균 온도는 301.2도입니다."가 출력됩니다.
# round(값, 1): 값을 소수 첫째 자리까지 반올림합니다.
average = sum(temperatures) / len(temperatures)
print(f"평균 온도는 {round(average, 1)}도입니다.")   # round()로 소수점 정리 + 1차시 f-string 복습

평균 온도는 301.2도입니다.


### 직접 해보기 — 온도 범위 계산하기
강의 자료 「리스트에서 최댓값·최솟값·평균 구하기」 절의 "직접 해보기" 상자입니다. 최고 온도와 최저 온도의 차이(온도 범위)를 계산하고 문장으로 출력합니다.

In [20]:
# [직접 해보기] 온도 범위(최고 온도 - 최저 온도)를 계산해 temp_range에 저장하고, 값을 출력해 확인합니다.
# 실행하면 17.2에 아주 가까운 값이 소수점 아래 여러 자리까지 길게 나옵니다(컴퓨터가 소수를 2진수로 계산하며 생기는 아주 작은 오차).
temp_range = max(temperatures) - min(temperatures)
print(temp_range)  # (중간 확인)

17.200000000000045


> **참고**
>
> 강의 자료 「리스트에서 최댓값·최솟값·평균 구하기」 절의 "직접 해보기" 상자에 이 계산식이 그대로 있습니다. 같은 절의 코드 블록에서 리스트 전체의 최댓값과 최솟값을 구한 함수 두 개를 다시 보세요 — 두 결과를 빼면 온도 범위가 됩니다.
>
> 정답 해설: 빈칸은 차례로 `max`, `min`. `max(temperatures) - min(temperatures)`는 312.6 - 295.4다. 출력에 소수점 아래 자리가 길게 붙는 것은 컴퓨터가 소수를 2진수로 저장하며 생기는 아주 작은 오차이고, 다음 셀의 서식 기호로 정리한다.
>
> 예상 결과: `17.200000000000045` (4단계에서 303.2를 추가한 6개 값 기준. 최댓값 312.6, 최솟값 295.4)

In [21]:
# [직접 해보기] 온도 범위를 소수 첫째 자리까지만 보이게 해서 문장으로 출력합니다.
# 실행하면 "온도 범위는 17.2도입니다."가 출력됩니다.
print(f"온도 범위는 {temp_range:.1f}도입니다.")

온도 범위는 17.2도입니다.


> **참고**
>
> 강의 자료 「리스트에서 최댓값·최솟값·평균 구하기」 절의 "직접 해보기" 상자에 있는 f-string을 다시 보세요. 중괄호 안에서 변수 이름 바로 뒤에 붙인 서식 기호가 "소수 첫째 자리까지만 보여 달라"는 뜻입니다.
>
> 정답 해설: 빈칸은 `:.1f`. `{temp_range:.1f}`는 값을 소수 첫째 자리까지 반올림해 보여 준다(`f`는 소수 형식이라는 뜻). 변수에 저장된 값 자체는 바뀌지 않고 보이는 모양만 바뀐다 — 5단계 `round(average, 1)`과 같은 목적이다.
>
> 예상 결과: `온도 범위는 17.2도입니다.`

## 6단계. 딕셔너리 만들기
**설명 포인트**: 리스트와 곧바로 비교 — "순서 대신 이름표(키)로 값을 구분한다".

**진행 방법**: 사람 딕셔너리(`person`) 두 셀로 감을 잡은 뒤 설비 딕셔너리로 넘어간다.

**예상 결과**: `{'이름': '지민', '나이': 15}` → `지민` → `{'설비번호': 'EQ-01', '공정명': '식각', '온도_섭씨': 301.2}`

### 따라 해보기 — 아주 간단한 딕셔너리
반도체 데이터로 들어가기 전에, 사람 한 명의 정보를 담은 가장 단순한 딕셔너리로 감을 잡습니다
(강의 자료 "먼저 아주 간단한 예로 감을 잡자"). 완성된 코드이니 실행만 해 보세요.

In [22]:
# 사람 한 명의 이름과 나이를 딕셔너리로 만들어 person에 저장하고 출력합니다.
# 실행하면 {'이름': '지민', '나이': 15}가 출력됩니다.
# 딕셔너리: 중괄호 { } 안에 키: 값 쌍을 콤마로 나열합니다. 키는 값에 붙이는 이름표입니다.
person = {"이름": "지민", "나이": 15}
print(person)

{'이름': '지민', '나이': 15}


In [23]:
# 이름표(키) "이름"으로 값을 꺼내 출력합니다.
# 실행하면 지민이 출력됩니다.
# 딕셔너리이름[키]: 리스트의 인덱스 대신 키를 대괄호 안에 넣어 값을 꺼냅니다.
print(person["이름"])

지민


### 반도체 데이터로 — 설비 1대를 딕셔너리로
같은 방식으로 설비 1대의 정보(설비번호, 공정명, 온도)를 딕셔너리로 표현합니다.

In [24]:
# 설비 1대의 정보(설비번호, 공정명, 온도)를 딕셔너리로 만들어 equipment에 저장하고 출력합니다.
# 실행하면 {'설비번호': 'EQ-01', '공정명': '식각', '온도_섭씨': 301.2}가 출력됩니다.
# 글자 값("EQ-01")은 따옴표로 감싸고, 숫자 값(301.2)은 따옴표 없이 씁니다. 키-값 쌍을 한 줄에 하나씩 적어도 됩니다.
equipment = {
    "설비번호": "EQ-01",
    "공정명": "식각",
    "온도_섭씨": 301.2,
}
print(equipment)

{'설비번호': 'EQ-01', '공정명': '식각', '온도_섭씨': 301.2}


## 7단계. 키로 값 접근하기
**어려워할 부분**: 없는 키에 접근하면 `KeyError`가 난다는 점을 실제로 `equipment["압력_Pa"]`를 실행해 보여주면 효과적.

**시연 방법**: 이 단계 마지막의 주석 처리된 셀에서 `#`을 지우고 실행해 `KeyError: '압력_Pa'`를 보여준 뒤 다시 `#`을 붙여 둔다(8단계에서 `압력_Pa`를 추가하기 전이어야 오류가 난다). 운영안 "예상 오개념"의 `KeyError: 0`(딕셔너리를 `[0]`으로 접근) 시연 줄도 같은 셀에 있다.

**예상 결과**: `EQ-01` → `301.2`

In [25]:
# 키 "설비번호"로 설비번호 값을 꺼내 출력합니다.
# 실행하면 EQ-01이 출력됩니다.
print(equipment["설비번호"])

EQ-01


In [26]:
# 키 "온도_섭씨"로 온도 값을 꺼내 출력합니다.
# 실행하면 301.2가 출력됩니다.
print(equipment["온도_섭씨"])

301.2


In [27]:
# [오류 주의] 딕셔너리에 없는 키를 쓰면 KeyError가 납니다. 이 셀은 실행해도 아무것도 나오지 않습니다.
# 아래 두 줄 중 하나의 맨 앞 #을 지우고 실행하면 KeyError가 나는 것을 직접 볼 수 있습니다.
# 확인한 뒤에는 다시 #을 붙여 두세요(노트북을 처음부터 다시 실행할 때 여기서 멈추지 않도록).
# print(equipment["압력_Pa"])   # 아직 "압력_Pa" 키가 없다 → KeyError: '압력_Pa'
# print(equipment[0])           # 딕셔너리는 인덱스(순서 번호)로 꺼낼 수 없다 → KeyError: 0

## 8단계. 값 수정하기 / 새 키 추가하기

**예상 결과**: `{'설비번호': 'EQ-01', '공정명': '식각', '온도_섭씨': 305.5, '압력_Pa': 1012.3}` → (직접 해보기) `{'설비번호': 'EQ-06', '공정명': '증착', '온도_섭씨': 303.4}` → `설비 EQ-06은(는) 증착 공정이며 온도는 303.4도입니다.` "직접 해보기" 셀은 `equipment`에 새 설비를 다시 저장하므로 그 뒤로 `equipment`는 EQ-06이다(11단계 도전 문제 2가 이 딕셔너리를 쓴다).

In [28]:
# 이미 있는 키("온도_섭씨")에는 새 값을 넣어 값을 바꾸고, 없던 키("압력_Pa")에는 값을 넣어 새 항목을 추가합니다.
# 실행하면 온도가 305.5로 바뀌고 맨 끝에 '압력_Pa': 1012.3이 붙은 딕셔너리가 출력됩니다.
# 딕셔너리이름[키] = 값: 키가 있으면 값을 바꾸고, 없으면 새 키-값 쌍을 추가합니다.
equipment["온도_섭씨"] = 305.5     # 기존 값 수정
equipment["압력_Pa"] = 1012.3      # 새 키 추가

print(equipment)

{'설비번호': 'EQ-01', '공정명': '식각', '온도_섭씨': 305.5, '압력_Pa': 1012.3}


### 직접 해보기 — 나만의 설비 딕셔너리로 소개 문장 만들기
강의 자료 「값 수정하기 / 새 키 추가하기」 절의 "직접 해보기" 상자입니다. 나만의 `equipment` 딕셔너리를 만들고, f-string으로 설비 소개 문장을 출력합니다.

In [29]:
# [직접 해보기] 나만의 설비 1대를 딕셔너리로 만들어 equipment에 다시 저장하고 출력합니다. 값은 원하는 설비로 바꿔도 됩니다.
# 실행하면 {'설비번호': 'EQ-06', '공정명': '증착', '온도_섭씨': 303.4}가 출력됩니다(값을 바꿨다면 바꾼 값).
# 같은 이름(equipment)에 새 딕셔너리를 저장하면 위에서 만든 설비 정보는 이 새 딕셔너리로 바뀝니다.
equipment = {"설비번호": "EQ-06", "공정명": "증착", "온도_섭씨": 303.4}
print(equipment)

{'설비번호': 'EQ-06', '공정명': '증착', '온도_섭씨': 303.4}


In [30]:
# [직접 해보기] 방금 만든 딕셔너리의 값을 f-string 문장 속에 넣어 설비를 소개합니다.
# 실행하면 "설비 EQ-06은(는) 증착 공정이며 온도는 303.4도입니다."가 출력됩니다.
print(f"설비 {equipment['설비번호']}은(는) {equipment['공정명']} 공정이며 온도는 {equipment['온도_섭씨']}도입니다.")

설비 EQ-06은(는) 증착 공정이며 온도는 303.4도입니다.


> **참고**
>
> 강의 자료 「값 수정하기 / 새 키 추가하기」 절의 "직접 해보기" 상자에 이 문장의 f-string이 그대로 있습니다. 딕셔너리에서 값을 꺼낼 때는 대괄호 안에 키를 넣고(「키로 값 접근하기」 절), f-string 바깥이 큰따옴표이면 안쪽 키는 작은따옴표로 감쌉니다(「종합 실습 — 나만의 설비 목록 만들기」의 "따옴표 규칙").
>
> 정답 해설: 빈칸은 차례로 `'공정명'`, `'온도_섭씨'`. 큰따옴표로 감싼 f-string 안에서 키에 큰따옴표를 또 쓰면 파이썬 3.12 이전 버전에서는 `SyntaxError`가 난다.
>
> 예상 결과: `설비 EQ-06은(는) 증착 공정이며 온도는 303.4도입니다.` (학생이 값을 바꿨다면 그 값)

## 9단계. 리스트 안에 딕셔너리 담기
**설명 포인트**: 이번 차시의 핵심 도약 지점. 4차시 Pandas의 표(행=딕셔너리, 표=리스트) 개념과 미리 연결해 언급한다.

**진행 방법**: 학생 딕셔너리의 리스트(`students`) 세 셀 → 설비 딕셔너리의 리스트(`equipment_list`) 네 셀.

**예상 결과**: `{'이름': '지민', '점수': 90}` → `90` → `하은` → `3` → `{'설비번호': 'EQ-01', '공정명': '식각', '온도_섭씨': 301.2}` → `301.2` → `EQ-02` → (직접 해보기) `포토`

### 따라 해보기 — 아주 간단한 딕셔너리의 리스트
학생 두 명의 정보를 담은 가장 단순한 "딕셔너리의 리스트"로 먼저 감을 잡습니다
(강의 자료 "먼저 아주 간단한 예로 감을 잡자"). 완성된 코드이니 한 셀씩 실행해 보세요.

In [31]:
# 학생 2명의 정보(딕셔너리 2개)를 리스트 하나에 담아 students에 저장하고, 첫 번째 학생을 출력합니다.
# 실행하면 {'이름': '지민', '점수': 90}이 출력됩니다 — 리스트에서 꺼낸 값 하나가 딕셔너리 하나입니다.
# 딕셔너리의 리스트: 리스트 [ ] 안에 딕셔너리 { }를 콤마로 구분해 여러 개 넣습니다.
students = [
    {"이름": "지민", "점수": 90},
    {"이름": "하은", "점수": 85},
]

print(students[0])              # 첫 번째 학생(딕셔너리 하나)

{'이름': '지민', '점수': 90}


In [32]:
# 첫 번째 학생(인덱스 0)의 "점수" 값을 꺼내 출력합니다.
# 실행하면 90이 출력됩니다. [인덱스]로 딕셔너리를 먼저 꺼내고, 이어서 [키]로 그 안의 값을 꺼냅니다.
print(students[0]["점수"])      # 첫 번째 학생의 점수

90


In [33]:
# 두 번째 학생(인덱스 1)의 "이름" 값을 꺼내 출력합니다.
# 실행하면 하은이 출력됩니다.
print(students[1]["이름"])      # 두 번째 학생의 이름

하은


### 반도체 데이터로 — 설비 3대를 딕셔너리의 리스트로
같은 방식으로 설비 여러 대를 "딕셔너리의 리스트"로 표현합니다. `equipment_list[1]["온도_섭씨"]`처럼
"몇 번째 설비"와 "무슨 이름표"를 순서대로 지정하면 원하는 값을 정확히 꺼낼 수 있습니다.

In [34]:
# 설비 3대의 정보를 딕셔너리의 리스트로 만들어 equipment_list에 저장하고, 설비 개수를 출력합니다.
# 실행하면 3이 출력됩니다 — 리스트 안의 딕셔너리 하나가 설비 1대입니다.
equipment_list = [
    {"설비번호": "EQ-01", "공정명": "식각", "온도_섭씨": 301.2},
    {"설비번호": "EQ-02", "공정명": "증착", "온도_섭씨": 308.7},
    {"설비번호": "EQ-03", "공정명": "포토", "온도_섭씨": 297.5},
]

print(len(equipment_list))              # 설비 개수

3


In [35]:
# 첫 번째 설비(인덱스 0)의 딕셔너리 전체를 출력합니다.
# 실행하면 {'설비번호': 'EQ-01', '공정명': '식각', '온도_섭씨': 301.2}가 출력됩니다.
print(equipment_list[0])                # 첫 번째 설비(딕셔너리 하나)

{'설비번호': 'EQ-01', '공정명': '식각', '온도_섭씨': 301.2}


In [36]:
# 첫 번째 설비의 "온도_섭씨" 값을 꺼내 출력합니다. "몇 번째 설비"를 먼저, "무슨 이름표"를 다음에 적습니다.
# 실행하면 301.2가 출력됩니다.
print(equipment_list[0]["온도_섭씨"])    # 첫 번째 설비의 온도

301.2


In [37]:
# 두 번째 설비(인덱스 1)의 "설비번호" 값을 꺼내 출력합니다.
# 실행하면 EQ-02가 출력됩니다.
print(equipment_list[1]["설비번호"])     # 두 번째 설비의 번호

EQ-02


### 직접 해보기 — 세 번째 설비의 공정명 꺼내기
강의 자료 「리스트 안에 딕셔너리 담기 — 여러 설비를 한 번에 표현하기」 절의 "직접 해보기" 상자입니다.

In [38]:
# [직접 해보기] 세 번째 설비의 "공정명" 값을 꺼내 출력합니다.
# 실행하면 포토가 출력됩니다 — 위 equipment_list에서 직접 찾아 맞는지 비교해 보세요.
print(equipment_list[2]["공정명"])

포토


> **참고**
>
> 강의 자료 「리스트 안에 딕셔너리 담기 — 여러 설비를 한 번에 표현하기」 절의 "직접 해보기" 상자에 이 코드가 그대로 있습니다. 인덱스는 0부터 세므로(「인덱싱 — 순서로 값 꺼내기」 절) "세 번째"의 인덱스는 3보다 하나 작습니다.
>
> 정답 해설: 빈칸은 `2`. `equipment_list[2]`로 세 번째 딕셔너리를 꺼낸 뒤 `["공정명"]`으로 그 안의 값을 꺼낸다.
>
> 예상 결과: `포토`

## 10단계(도전). 종합 실습 — 나만의 설비 목록 만들기
**시연 방법**: 학생 한 명에게 설비 이름을 즉석에서 물어보고 함께 채워 넣으면 참여도가 높아진다.

**예상 결과**: `EQ-04 설비는 세정 공정, 온도는 299.0도입니다.` → `EQ-05 설비는 산화 공정, 온도는 302.4도입니다.` 학생용은 두 번째 설비의 설비번호·공정명과, 두 번째 문장의 키 하나가 빈칸이다.

In [39]:
# 나만의 설비 2대를 딕셔너리의 리스트 my_equipment로 만들고, 첫 번째 설비를 소개하는 문장을 출력합니다.
# 실행하면 "EQ-04 설비는 세정 공정, 온도는 299.0도입니다."가 출력됩니다.
# f-string 바깥을 큰따옴표로 감쌌으므로 안쪽 딕셔너리 키는 작은따옴표('설비번호')로 씁니다.
# print( ) 괄호 안에서는 f-string을 두 줄로 나눠 적어도 한 문장으로 이어져 출력됩니다.
my_equipment = [
    {"설비번호": "EQ-04", "공정명": "세정", "온도_섭씨": 299.0},
    {"설비번호": "EQ-05", "공정명": "산화", "온도_섭씨": 302.4},
]

print(f"{my_equipment[0]['설비번호']} 설비는 {my_equipment[0]['공정명']} 공정, "
      f"온도는 {my_equipment[0]['온도_섭씨']}도입니다.")

EQ-04 설비는 세정 공정, 온도는 299.0도입니다.


In [40]:
# 두 번째 설비(인덱스 1)를 소개하는 문장을 출력합니다.
# 실행하면 "EQ-05 설비는 산화 공정, 온도는 302.4도입니다."가 출력됩니다.
print(f"{my_equipment[1]['설비번호']} 설비는 {my_equipment[1]['공정명']} 공정, "
      f"온도는 {my_equipment[1]['온도_섭씨']}도입니다.")

EQ-05 설비는 산화 공정, 온도는 302.4도입니다.


## 11단계. 오늘의 학습을 한 문장으로 정리하기
**진행 방법**: 학생 두세 명에게 자기 문장을 소리 내어 말하게 한다. 문장이 나오지 않는 학생에게는 "리스트와 딕셔너리는 값을 무엇으로 구분하나요?"만 물어보면 된다.
**설명 포인트**: 결과 해석 문장 쓰기는 1차시부터 10차시까지 매 차시 빠지지 않는 고정 활동이다(docs/curriculum.md 「차시 간 연결 원칙」). 코드를 친 것으로 끝내지 않고 자기 말로 바꿔 말해보게 하는 것이 이 과정의 목표 — "데이터로 공정 상태를 설명할 수 있는 사람" — 에 직접 닿는 활동이므로 시간이 모자라도 2~3분은 반드시 확보한다.

> (예시 답안) 리스트는 순서로 값을 구분하고, 딕셔너리는 이름표(키)로 값을 구분한다. 리스트 안에 딕셔너리를 담으면 여러 설비 정보를 한 번에 표현할 수 있다.

## 오류 대처 방법
- `IndexError` 발생 시: `len()`으로 리스트 길이를 먼저 확인.
- `KeyError` 발생 시: `print(딕셔너리)`로 전체 키를 먼저 확인.
- `SyntaxError`(f-string 안 따옴표 중복): 바깥이 큰따옴표면 안쪽 딕셔너리 키는 작은따옴표(`'설비번호'`)로 쓰도록 안내(강의 "따옴표 규칙").

### 도전 문제 1 — 온도만 모은 리스트로 최고 온도 찾기 (빠른 학습자용)
강의 자료 「도전 실습」의 도전 문제 1입니다. 9단계의 `equipment_list`에서 온도만 꺼내 새 리스트를 만들고, 그 리스트의 최댓값을 구합니다. 핵심 실습(1~10단계)을 마친 뒤 시간이 남으면 풀어 보세요.

이전 버전의 강사용 전용 "확장 실습" 셀을 세 노트북 공통 셀로 옮긴 것이다. 온도만 모은 새 리스트를 만들어 `max()`를 적용해보게 하면 3차시(반복문으로 자동화) 예고가 된다.

In [41]:
# [도전 문제 1] 설비 3대의 온도만 꺼내 새 리스트 temps_only에 담고 출력합니다.
# 실행하면 [301.2, 308.7, 297.5]가 출력됩니다.
temps_only = [equipment_list[0]["온도_섭씨"], equipment_list[1]["온도_섭씨"], equipment_list[2]["온도_섭씨"]]
print(temps_only)

[301.2, 308.7, 297.5]


> **참고**
>
> 강의 자료 「도전 실습」 절의 "도전 문제 1" 힌트에 온도만 모은 새 리스트를 만드는 코드가 적혀 있습니다. 대괄호 안에 값을 콤마로 나열하면 리스트가 되고, 각 값 자리에는 "몇 번째 설비"(인덱스)와 "무슨 이름표"(키)를 차례로 적습니다(「리스트 안에 딕셔너리 담기 — 여러 설비를 한 번에 표현하기」 절).
>
> 정답 해설: 빈칸은 차례로 `1`, `2`. 설비 3대의 인덱스는 0, 1, 2이므로 두 번째·세 번째 설비는 `[1]`, `[2]`다.
>
> 예상 결과: `[301.2, 308.7, 297.5]`

In [42]:
# [도전 문제 1] 온도만 모은 리스트에서 가장 큰 값을 구합니다.
# 실행하면 308.7이 출력됩니다 — temps_only에서 몇 번째 값인지 보고 어느 설비인지 확인해 보세요.
print(max(temps_only))

308.7


> **참고**
>
> 강의 자료 「도전 실습」 절의 "도전 문제 1"과 「리스트에서 최댓값·최솟값·평균 구하기」 절을 다시 보세요. 리스트 전체에서 가장 큰 값을 돌려주는 내장 함수를 온도만 모은 리스트에 적용합니다.
>
> 정답 해설: 빈칸은 `max`. `max(temps_only)`는 308.7을 돌려준다. 이 값은 `temps_only`의 인덱스 1에 있으므로 `equipment_list[1]`, 즉 EQ-02가 온도가 가장 높은 설비다. 이렇게 "몇 번째인지"를 눈으로 찾는 일을 3차시에서 반복문으로 자동화한다.
>
> 예상 결과: `308.7` (13단계 AI 예시 `max(..., key=lambda ...)`가 찾은 EQ-02와 같은 설비)

### 도전 문제 2 — 딕셔너리에 새 키 추가하기 (빠른 학습자용)
강의 자료 「도전 실습」의 도전 문제 2입니다. 설비 딕셔너리 `equipment`에 새 키를 하나 추가하고, 전체 딕셔너리를 다시 출력해 잘 추가됐는지 확인합니다.

In [43]:
# [도전 문제 2] 설비 딕셔너리 equipment에 판정 결과를 담는 새 키를 추가하고, 전체 딕셔너리를 다시 출력합니다.
# 값 1은 1차시에서 배운 규약으로 "합격"을 뜻합니다(-1은 불합격).
# 실행하면 맨 끝에 새 키와 값 1이 붙은 딕셔너리가 출력됩니다.
equipment["합격여부"] = 1
print(equipment)

{'설비번호': 'EQ-06', '공정명': '증착', '온도_섭씨': 303.4, '합격여부': 1}


> **참고**
>
> 강의 자료 「도전 실습」 절의 "도전 문제 2"에 추가할 키와 값이 적혀 있습니다. 없던 키에 값을 대입하면 새 항목이 추가된다는 것은 「값 수정하기 / 새 키 추가하기」 절에서 배웠습니다. 키는 글자(문자열)이므로 따옴표로 감쌉니다.
>
> 정답 해설: 빈칸은 `"합격여부"`. `equipment["합격여부"] = 1`처럼 없던 키에 값을 대입하면 딕셔너리 끝에 새 키-값 쌍이 붙는다. 값 1은 합격, -1은 불합격(1차시 규약).
>
> 예상 결과: `{'설비번호': 'EQ-06', '공정명': '증착', '온도_섭씨': 303.4, '합격여부': 1}` (8단계 "직접 해보기"에서 만든 설비 기준 — 학생이 값을 바꿨다면 그 값)

## 12단계. AI에게 질문하며 더 알아보기
**설명 포인트**: 리스트/튜플, 딕셔너리 키 제약 같은 질문은 4차시 Pandas의 인덱스 개념과도
연결되니 답변을 들을 때 미리 짚어주면 좋다.

질문 예시:
- "파이썬 리스트와 튜플은 어떻게 다른가요?"
- "딕셔너리에서 키(key)로 쓸 수 있는 값과 쓸 수 없는 값은 무엇인가요?"
- "딕셔너리 안에 리스트를 담을 수도 있나요?"
- "리스트의 append()와 insert()는 어떻게 다른가요?"

## 13단계. AI에게 코드 생성 요청하고 직접 실행해보기
**설명 포인트**: `max(..., key=lambda ...)`는 오늘 배우지 않은 문법이다 — "AI가 준 코드도 이해하고
써야 한다"는 메시지를 전달하기 좋은 타이밍이다.

프롬프트 예시: "설비 정보 딕셔너리가 여러 개 담긴 리스트에서, 온도가 가장 높은 설비 하나만
찾아주는 코드를 만들어줘."

아래는 AI가 생성해줄 수 있는 예시 코드와 실행 결과다.

**주의**: 강의 자료의 예시 코드는 목록 이름을 `sample_list`로 지어 9단계에서 만든 `equipment_list`(공정명 포함)를 덮어쓰지 않습니다. AI가 준 코드가 `equipment_list = [...]`처럼 같은 이름을 쓰면 내 설비 목록이 새 목록으로 바뀌니, `sample_list` 같은 다른 이름으로 바꿔서 실행하세요.

강의 예시는 목록 이름을 `sample_list`로 지어 9단계 `equipment_list`를 덮어쓰지 않는다(1차 작업의 복원 셀은 필요 없어져 제거했다). 학생이 받은 AI 코드가 `equipment_list = [...]`를 쓰면 이름을 바꾸게 하거나, 9단계 셀을 다시 실행하게 한다.

In [44]:
# AI가 만들어 줄 수 있는 코드 예시입니다(강의 자료와 같음). 설비 3대 중 온도가 가장 높은 설비를 찾아 문장으로 출력합니다.
# 실행하면 "가장 온도가 높은 설비는 EQ-02이고, 온도는 308.7도입니다."가 출력됩니다.
# max(리스트, key=lambda eq: eq["온도_섭씨"]): 각 딕셔너리의 "온도_섭씨" 값을 기준으로 가장 큰 항목을 고릅니다(오늘 배우지 않은 문법).
# 목록 이름을 sample_list로 지어, 9단계에서 만든 equipment_list(공정명 포함)를 덮어쓰지 않습니다.
sample_list = [
    {"설비번호": "EQ-01", "온도_섭씨": 301.2},
    {"설비번호": "EQ-02", "온도_섭씨": 308.7},
    {"설비번호": "EQ-03", "온도_섭씨": 297.5},
]

hottest = max(sample_list, key=lambda eq: eq["온도_섭씨"])
print(f"가장 온도가 높은 설비는 {hottest['설비번호']}이고, 온도는 {hottest['온도_섭씨']}도입니다.")

가장 온도가 높은 설비는 EQ-02이고, 온도는 308.7도입니다.


## 14단계. 연습문제 — 압력 리스트와 새 설비 딕셔너리
**설명 포인트**: 7단계(1차시 온도·설비 문장 만들기)와 같은 목적의 단계다. 오늘 배운 리스트
생성·통계 계산(`max`/`min`/`sum`/`len`)과 딕셔너리 키 추가를 새로운 데이터(압력)로 한 번 더
반복 연습시킨다. 빠른 학습자에게는 도전(새 설비 딕셔너리)까지, 느린 학습자에게는 리스트 통계
계산까지만 요구해도 충분하다.

**예상 결과**: `[1010.2, 1005.4, 1022.9, 998.7, 1011.0]` → `1022.9 998.7` → `최댓값: 1022.9, 최솟값: 998.7, 평균: 1009.6`. 도전: `{'설비번호': 'EQ-04', '공정명': '세정', '온도_섭씨': 299.9}` → `{'설비번호': 'EQ-04', '공정명': '세정', '온도_섭씨': 299.9, '압력_Pa': 1009.64}`(강의 연습문제 "정답 보기"와 같은 결과).

In [45]:
# 오늘 측정한 압력 값 5개를 리스트로 만들어 pressures에 저장하고, 잘 저장됐는지 출력해 확인합니다.
# 실행하면 [1010.2, 1005.4, 1022.9, 998.7, 1011.0]이 출력됩니다.
pressures = [1010.2, 1005.4, 1022.9, 998.7, 1011.0]
print(pressures)  # (중간 확인)

[1010.2, 1005.4, 1022.9, 998.7, 1011.0]


In [46]:
# 압력의 최댓값과 최솟값을 구해 highest_p, lowest_p에 저장하고, 두 값을 출력해 확인합니다.
# 실행하면 1022.9 998.7이 한 줄에 출력됩니다.
highest_p = max(pressures)
lowest_p = min(pressures)
print(highest_p, lowest_p)  # (중간 확인)

1022.9 998.7


In [47]:
# 평균 압력을 계산해 average_p에 저장하고, 최댓값·최솟값·평균을 한 문장으로 출력합니다.
# 실행하면 "최댓값: 1022.9, 최솟값: 998.7, 평균: 1009.6"이 출력됩니다.
average_p = sum(pressures) / len(pressures)

print(f"최댓값: {highest_p}, 최솟값: {lowest_p}, 평균: {round(average_p, 1)}")

최댓값: 1022.9, 최솟값: 998.7, 평균: 1009.6


### 도전. 새 설비 딕셔너리에 압력 추가하기
**시연 방법**: 방금 계산한 `average_p`를 그대로 새 딕셔너리의 값으로 재사용하는 것을 보여주면,
"한 계산 결과를 다른 자료구조에 다시 담을 수 있다"는 감각을 심어주기 좋다.

In [48]:
# 새 설비 EQ-04의 정보를 딕셔너리 eq04로 만들고, 잘 만들어졌는지 출력해 확인합니다.
# 실행하면 {'설비번호': 'EQ-04', '공정명': '세정', '온도_섭씨': 299.9}가 출력됩니다.
# 딕셔너리는 6단계처럼 여러 줄로 적어도 되고, 이렇게 한 줄로 적어도 됩니다.
eq04 = {"설비번호": "EQ-04", "공정명": "세정", "온도_섭씨": 299.9}
print(eq04)  # (중간 확인)

{'설비번호': 'EQ-04', '공정명': '세정', '온도_섭씨': 299.9}


In [49]:
# 방금 계산한 평균 압력(average_p)을 "압력_Pa"라는 새 키로 eq04에 추가하고 출력합니다.
# 실행하면 맨 끝에 '압력_Pa': 1009.64가 붙은 딕셔너리가 출력됩니다.
eq04["압력_Pa"] = average_p
print(eq04)

{'설비번호': 'EQ-04', '공정명': '세정', '온도_섭씨': 299.9, '압력_Pa': 1009.64}


## 15단계. AI로 재미있는 미니 프로그램 만들기 🎉 — 오늘의 럭키 설비 뽑기
**설명 포인트**: 8단계(1차시 공정 운세 뽑기)와 같은 목적의 마무리 단계다. 정확한 코드 자체보다
"오늘 만든 리스트·딕셔너리를 AI와 함께 재미있는 프로그램으로 확장해보는 경험"을 즐기도록 유도한다.

프롬프트 예시: "설비 정보 딕셔너리가 여러 개 담긴 리스트(equipment_list)에서, random.choice()로
하나를 무작위로 뽑아서 '오늘의 럭키 설비'라는 제목과 함께 설비번호·공정명·온도를 예쁘게 출력하는
파이썬 코드를 만들어줘."

**주의 안내**: `random` 모듈은 오늘 처음 보는 표현이다 — 리스트·딕셔너리는 오늘 배운 내용이니,
`random.choice()`가 리스트에서 하나를 무작위로 골라준다는 정도만 짚어주면 충분하다.

아래는 AI가 생성해줄 수 있는 예시 코드다(강의 자료 예시와 같은 코드). `import random` 아래의 `random.seed(7)` 줄로 결과를 고정해 두어 몇 번을 실행해도 **EQ-03(포토, 297.5도)**이 뽑힌다(강의 "실행 결과"와 같다). **seed 줄을 지우면 실행할 때마다 뽑히는 설비가 달라진다** — 시연에서 seed 줄을 지우고 여러 번 실행해 무작위를 보여줘도 좋다. 네 번째 설비(EQ-04, 세정, 299.9)는 14단계 `eq04`와 같은 값을 직접 적어 넣은 것이다.

In [50]:
# AI가 만들어 줄 수 있는 "오늘의 럭키 설비 뽑기" 코드 예시입니다(강의 자료와 같음). 설비 4대 중 하나를 무작위로 골라 정보를 출력합니다.
# 실행하면 제목 줄과 뽑힌 설비의 설비번호·공정명·온도가 출력됩니다. random.seed(7) 줄 때문에 몇 번을 실행해도 같은 설비가 뽑히고, 그 줄을 지우면 실행할 때마다 바뀝니다.
# import random: 무작위 기능이 담긴 random 모듈을 불러옵니다. random.choice(리스트)는 리스트에서 하나를 무작위로 고릅니다.
# random.seed(숫자): 무작위 뽑기의 출발점을 정해 두어, 같은 숫자를 쓰면 항상 같은 결과가 나오게 합니다.
import random
random.seed(7)  # 실행할 때마다 같은 결과가 나오도록 고정

equipment_list = [
    {"설비번호": "EQ-01", "공정명": "식각", "온도_섭씨": 301.2},
    {"설비번호": "EQ-02", "공정명": "증착", "온도_섭씨": 308.7},
    {"설비번호": "EQ-03", "공정명": "포토", "온도_섭씨": 297.5},
    {"설비번호": "EQ-04", "공정명": "세정", "온도_섭씨": 299.9},
]

lucky = random.choice(equipment_list)
print("🎉 오늘의 럭키 설비 🎉")
print(f"설비번호: {lucky['설비번호']}")
print(f"공정명: {lucky['공정명']}")
print(f"온도: {lucky['온도_섭씨']}도")

🎉 오늘의 럭키 설비 🎉
설비번호: EQ-03
공정명: 포토
온도: 297.5도
