# 1차시 강사용 Notebook — 반도체 공정과 데이터 처음 만나기 + 변수·출력

학생용 Notebook과 동일한 흐름이며, 예상 결과와 설명 포인트를 함께 담았습니다.

오늘은 Pandas 없이 진행합니다(Pandas는 4차시부터). 강의 자료에서 데이터를 눈으로 미리 살펴본 뒤,
그 결과(합격 32건/불합격 8건)를 변수에 저장하는 것으로 시작합니다.

코드는 강의 자료(`lectures/week01/index.html`)의 코드 블록과 같습니다. 강의에서는 한 블록으로 보여준
코드도 여기서는 결과가 하나씩 보이도록 셀을 나눴고, 각 셀 맨 위에 초보자용 설명 주석을 달았습니다
(학생용과 같은 주석).

## 1단계. 변수 만들고 값 확인하기
**설명 포인트**: `=`는 수학의 '같다'가 아니라 대입 연산자임을 강조. 칠판에 상자 그림을 그려 '오른쪽 값이 왼쪽 이름의 상자에 들어간다'고 설명하면 효과적.

**예상 결과**: `32`, `8`이 한 줄씩 출력된다.

In [1]:
# 합격 개수(32)와 불합격 개수(8)를 변수에 저장한 뒤, print()로 다시 꺼내 출력합니다.
# 실행하면 32와 8이 한 줄에 하나씩 출력됩니다.
# print(): 괄호 안의 값을 화면에 보여주는 함수입니다.
# 값에 이름을 붙여 저장한다(대입).
pass_count = 32
fail_count = 8

# 이름(변수)만 적으면 그 안에 든 값을 다시 꺼내 쓸 수 있다.
print(pass_count)
print(fail_count)

32
8


### 따라 해보기 — 자료형 확인하기
**설명 포인트**: 강의 자료 "자료형 확인하기" 코드와 같다(강의 STEP 02의 3번 "자료형 확인하기"에 해당).
문자열은 반드시 따옴표로 감싸야 하며, `equipment = EQ-03`처럼 따옴표를 빼면
`SyntaxError: leading zeros in decimal integer literals are not permitted`가 난다는 점을 함께 짚는다.

**예상 결과**: `<class 'float'>`, `<class 'str'>`, `<class 'bool'>`이 차례로 출력된다.

In [2]:
# 실수·문자열·불리언 값을 변수 세 개에 저장하고, type()으로 각각의 자료형을 확인합니다.
# 실행하면 <class 'float'>, <class 'str'>, <class 'bool'>이 차례로 출력됩니다.
# type(): 괄호 안 값의 자료형(종류)을 알려주는 함수입니다.
temperature = 300.1        # 실수(float)
equipment = "EQ-03"        # 문자열(str) — 따옴표로 감싼다
is_pass = True              # 불리언(bool) — True/False만 가능

print(type(temperature))
print(type(equipment))
print(type(is_pass))

<class 'float'>
<class 'str'>
<class 'bool'>


## 2단계. f-string으로 문장 만들기
**어려워할 부분**: 문자열 앞의 `f`를 빼먹으면 중괄호가 그대로 출력된다는 점을 `print("합격 {pass_count}건")`과 비교해 직접 보여주면 효과적.

강의 자료 순서대로 콤마 나열 출력 → f-string 기본 → f-string 안에서 계산하기(`:.1f`) 세 셀로 진행하고,
끝으로 강의 "직접 해보기" 상자(`equipment`·`temperature`로 나만의 문장 만들기)를 빈칸 셀로 풀게 한다.

### 따라 해보기 — print()로 여러 값 한 번에 출력하기
**예상 결과**: `합격: 32 불합격: 8` — 값 사이에 공백이 저절로 들어가 문장을 매끄럽게 쓰기 어렵다는 점이 f-string으로 넘어가는 동기가 된다.

In [3]:
# print() 안에 콤마(,)로 글자와 변수를 나열해 한 줄에 출력합니다.
# 실행하면 "합격: 32 불합격: 8"이 출력됩니다 — 값 사이에 공백이 하나씩 들어간 것을 확인해 보세요.
print("합격:", pass_count, "불합격:", fail_count)

합격: 32 불합격: 8


### f-string 기본 — 문장 속에 값 끼워 넣기
**예상 결과**: `오늘 합격은 32건, 불합격은 8건입니다.`

In [4]:
# f-string으로 문장 속 원하는 위치에 변수 값을 끼워 넣어 출력합니다.
# 실행하면 "오늘 합격은 32건, 불합격은 8건입니다."가 출력됩니다.
# f-string: 문자열 앞에 f를 붙이고, 값이 들어갈 자리에 {변수}를 적습니다.
print(f"오늘 합격은 {pass_count}건, 불합격은 {fail_count}건입니다.")

오늘 합격은 32건, 불합격은 8건입니다.


### 따라 해보기 — f-string 안에서 계산하기
**설명 포인트**: 콜론 뒤 `.1f` = 소수 첫째 자리까지. 빠른 학습자에게는 `:.2f`, `:.0f`로 바꿔 보게 한다(운영안 빠른 학습자용 과제).

**예상 결과**: `전체 40건 중 불합격률은 20.0%입니다.`

In [5]:
# 전체 건수(total)와 불합격률(fail_rate)을 계산한 뒤, 불합격률을 소수 첫째 자리까지 출력합니다.
# 실행하면 "전체 40건 중 불합격률은 20.0%입니다."가 출력됩니다.
# {fail_rate:.1f}: 콜론(:) 뒤의 .1f는 "소수 첫째 자리까지 보여 달라"는 서식입니다.
total = pass_count + fail_count
fail_rate = fail_count / total * 100

print(f"전체 {total}건 중 불합격률은 {fail_rate:.1f}%입니다.")

전체 40건 중 불합격률은 20.0%입니다.


### 직접 해보기 — 설비 이름·온도로 나만의 f-string 문장 만들기
**설명 포인트**: 강의 "직접 해보기" 상자의 예시 문장을 그대로 셀로 옮겼다. 1단계 자료형 셀에서 만든 변수를
다시 쓰므로, 1단계부터 순서대로 실행하지 않았으면 `NameError`가 난다(강의 "체크포인트 — 셀 실행 순서"와 연결).
학생용은 문자열 앞 `f`와 온도 변수 이름이 빈칸이다.

**예상 결과**: `EQ-03 설비의 온도는 300.1도입니다.`

In [6]:
# 1단계에서 만든 설비 이름 변수와 온도 변수를 f-string 문장에 끼워 넣어 출력합니다.
# 실행하면 "EQ-03 설비의 온도는 300.1도입니다."가 출력됩니다.
print(f"{equipment} 설비의 온도는 {temperature}도입니다.")

EQ-03 설비의 온도는 300.1도입니다.


> **참고**
> - 따옴표 앞 빈칸: 강의 자료 "f-string으로 문장 속에 값 끼워 넣기" 절의 "사용법" 줄을 다시 보세요.
>   따옴표 앞에 글자 하나를 붙여야 중괄호 `{ }` 안의 변수 이름이 그 값으로 바뀝니다. 빼먹으면 중괄호가 글자 그대로 출력됩니다
>   ("주의할 점 & 자주 발생하는 오류" 절의 "주의 — f-string 흔한 실수").
> - 중괄호 안 빈칸: 강의 자료 "자료형 — 정수·실수(숫자형), 문자열형, 불리언" 절의 "자료형 확인하기" 코드에서
>   300.1을 저장한 변수 이름을 찾아보세요. 중괄호 안에 변수 이름을 적으면 그 변수에 든 값이 문장 속에 끼워집니다.
>
> **정답 해설:** 따옴표 앞에 `f`, 중괄호 안에 `temperature`를 채운다. `f`가 있어야 `{equipment}`·`{temperature}`가
> 각각 `EQ-03`, `300.1`로 바뀐다. 실제 실행 결과: `EQ-03 설비의 온도는 300.1도입니다.`

## 3단계. input()으로 값 입력받기
**시연 방법**: 실제 수업에서는 아래 코드를 그대로 실행해 학생이 입력하는 과정을 보여준다.
```python
name = input("이름을 입력하세요: ")
```
이 노트북은 `validate_notebooks.py`로 자동 실행되므로, `input()`이 멈추지 않도록 아래 셀에서는 예시 값을 직접 대입한다
(`# 실제로는 input(...)` 주석이 붙은 줄).

**예상 결과**: `안녕하세요, 지민님! 반갑습니다.`

In [7]:
# input()으로 이름을 입력받아 name에 저장하고, f-string으로 인사 문장을 출력합니다.
# 실행하면 "안녕하세요, 지민님! 반갑습니다."처럼 입력한 이름이 들어간 문장이 출력됩니다.
# input("질문"): 화면에 질문을 보여주고, 키보드로 입력한 내용을 결과값으로 돌려줍니다.
name = "지민"  # 실제로는 input("이름을 입력하세요: ")
print(f"안녕하세요, {name}님! 반갑습니다.")

안녕하세요, 지민님! 반갑습니다.


### 따라 해보기 — 입력값을 숫자로 바꾸기
**설명 포인트**: 강의 자료의 "가장 중요한 주의사항" — `input()`의 결과는 항상 문자열. 첫 셀의 `(중간 확인)` 줄로
`<class 'str'>`을 눈으로 확인시킨 뒤 `int()`로 바꾼다. 두 번째 셀 마지막 주석 줄의 `#`을 지우고 실행하면
`TypeError: can only concatenate str (not "int") to str`가 나는 것을 시연할 수 있다(시연 후 다시 `#`을 붙여 둔다).

**예상 결과**(예시 입력값 24): `<class 'str'>` → `내년이면 25살이 되네요!`

In [8]:
# 나이를 입력받아 age_text에 저장하고, 그 자료형을 확인합니다.
# 실행하면 <class 'str'>이 출력됩니다 — 숫자를 입력해도 input()의 결과는 문자열입니다.
age_text = "24"  # 실제로는 input("나이를 입력하세요: ") — age_text는 항상 문자열!
print(type(age_text))  # (중간 확인)

<class 'str'>


In [9]:
# int()로 문자열 age_text를 정수 age로 바꾼 뒤, 1을 더해 내년 나이를 출력합니다.
# 실행하면 "내년이면 25살이 되네요!"가 출력됩니다(입력값 24 기준).
# int(): 괄호 안의 값을 정수로 바꾸는 함수입니다. 소수점이 있는 숫자는 float()를 씁니다.
age = int(age_text)                        # 문자열 → 정수로 변환

print(f"내년이면 {age + 1}살이 되네요!")

# 아래 줄 맨 앞의 #을 지우고 실행하면 TypeError가 납니다(문자열과 숫자는 더할 수 없습니다).
# print(age_text + 1)

내년이면 25살이 되네요!


## 4단계(도전). 나만의 자기소개 만들기
**시연 방법**: 학생 한 명을 지목해 실시간으로 입력받아 결과를 함께 확인하면 좋다.

**예상 결과**(강의 자료 예시 입력값 하은 / 식각):
```
안녕하세요! 저는 하은입니다.
오늘 배운 공정 중에서는 '식각' 공정이 가장 흥미로웠어요.
```

In [10]:
# 이름과 좋아하는 공정을 입력받아 변수 두 개에 저장하고, 자기소개 문장 두 줄을 출력합니다.
# 실행하면 "안녕하세요! 저는 하은입니다."와 좋아하는 공정 문장이 출력됩니다(입력값: 하은 / 식각).
my_name = "하은"  # 실제로는 input("이름을 입력하세요: ")
favorite_process = "식각"  # 실제로는 input("좋아하는 공정을 입력하세요(증착/식각/포토/세정/산화 중 하나): ")

print(f"안녕하세요! 저는 {my_name}입니다.")
print(f"오늘 배운 공정 중에서는 '{favorite_process}' 공정이 가장 흥미로웠어요.")

안녕하세요! 저는 하은입니다.
오늘 배운 공정 중에서는 '식각' 공정이 가장 흥미로웠어요.


### 도전 문제 1 — 합격률 계산해 출력하기 (빠른 학습자용)
**설명 포인트**: 강의 STEP 03 "도전 실습"의 세 줄을 두 셀(계산 / 출력)로 나눴다. 종합 실습을 먼저 끝낸 학생에게
제시하고, 나머지는 건너뛰고 5단계로 넘어가도 된다. 2단계 "f-string 안에서 계산하기"에서 불합격률을 구한 식을
합격률로 바꾸기만 하면 된다는 점을 연결해 준다. 학생용은 강의 본문에 나온 연산자·변수 이름·서식 일부가 빈칸이다.

**예상 결과**: `40 80.0` → `합격률은 80.0%입니다.`

In [11]:
# 전체 건수(total)와 합격률(pass_rate)을 계산해 변수에 저장하고, 두 값을 출력해 확인합니다.
# 실행하면 40 80.0이 출력됩니다 — 합격률은 100을 곱한 백분율(%) 숫자입니다.
total = pass_count + fail_count
pass_rate = pass_count / total * 100
print(total, pass_rate)  # (중간 확인)

40 80.0


> **참고**
> - 첫 번째 빈칸(전체 건수): 강의 자료 "도전 실습" 절의 첫 줄, 또는 "f-string으로 문장 속에 값 끼워 넣기" 절의
>   "f-string 안에서 계산하기" 코드 첫 줄을 다시 보세요. 두 변수 사이에 계산 기호 하나를 넣으면 계산한 결과가 왼쪽 이름에 저장됩니다.
> - 두 번째 빈칸(합격률): 강의 자료 "도전 실습" 절의 둘째 줄을 보세요. 2단계에서 불합격률을 `fail_count / total * 100`으로
>   구한 것과 같은 모양이고, 나누어지는 앞자리만 1단계에서 합격 개수를 저장한 변수로 바뀝니다.
>
> **정답 해설:** 첫 빈칸은 `+`(합격 32 + 불합격 8 = 전체 40), 둘째 빈칸은 `pass_count`(32 ÷ 40 × 100 = 80.0).
> 실제 실행 결과: `40 80.0`

In [12]:
# 계산한 합격률을 소수 첫째 자리까지 보여주는 f-string 문장으로 출력합니다.
# 실행하면 "합격률은 80.0%입니다."가 출력됩니다.
print(f"합격률은 {pass_rate:.1f}%입니다.")

합격률은 80.0%입니다.


> **참고**
> - 서식 빈칸: 강의 자료 "f-string으로 문장 속에 값 끼워 넣기" 절의 "소수점 자리수 지정" 줄(또는 "도전 실습" 절 셋째 줄)을
>   다시 보세요. 중괄호 안에서 변수 이름 뒤에 콜론을 쓰고 서식을 붙이면, 값을 소수 몇째 자리까지 보여줄지 정할 수 있습니다.
>
> **정답 해설:** `.1f`를 채운다(소수 첫째 자리까지). 서식 없이 `{pass_rate}`만 써도 지금은 `80.0`이 나오지만,
> `:.1f`는 계산 결과의 소수 자리가 길어도 첫째 자리로 맞춰 준다(`:.2f`로 바꾸면 `80.00`). 실제 실행 결과: `합격률은 80.0%입니다.`

## 5단계. AI에게 질문하며 더 알아보기
**설명 포인트**: AI 챗봇을 "옆자리 조교"처럼 활용하는 습관을 들이도록 독려한다. 질문 예시를
칠판에 적어주고, 학생 한 명을 지목해 실제로 답변을 받아보게 하면 효과적이다.

질문 예시:
- "파이썬에서 `=`와 `==`는 어떻게 다른가요?"
- "f-string 서식 옵션을 더 알려주세요."
- "input()을 실제 프로그램에서는 어떻게 안전하게 처리하나요?"
- "웨이퍼·다이·칩 관계를 다른 비유로 설명해주세요."

## 6단계. AI에게 코드 생성 요청하고 직접 실행해보기
**설명 포인트**: AI가 만든 코드에는 아직 배우지 않은 문법(`if`/`else`)이 섞여 나올 수 있다는 점을
강조한다 — "AI 코드를 그대로 베끼지 말고 이해하고 써야 한다"는 메시지를 전달하기 좋은 타이밍이다.

프롬프트 예시: "pass_count, fail_count 변수로 합격률을 계산해서 90% 이상이면 '정상', 아니면
'점검 필요'라고 출력하는 코드를 만들어줘."

아래는 AI가 생성해줄 수 있는 예시 코드와 실행 결과다(강의 자료 예시와 같게 맨 위에서 `pass_count`,
`fail_count`를 다시 저장하므로 이 셀만 따로 실행해도 동작한다). 학생용 Notebook의 같은 위치는
AI가 만든 코드를 붙여넣는 빈 셀이다.

**예상 결과**: `합격률 80.0% → 점검 필요`

In [13]:
# AI가 만들어 줄 수 있는 코드 예시입니다. 합격률을 계산해 90% 이상이면 "정상", 아니면 "점검 필요"를 출력합니다.
# 실행하면 "합격률 80.0% → 점검 필요"가 출력됩니다.
# if/else(조건문): 조건이 맞으면 if 아래 줄을, 아니면 else 아래 줄을 실행합니다(3차시에서 자세히 배웁니다).
pass_count = 32
fail_count = 8
total = pass_count + fail_count
pass_rate = pass_count / total * 100

if pass_rate >= 90:
    print(f"합격률 {pass_rate:.1f}% → 정상")
else:
    print(f"합격률 {pass_rate:.1f}% → 점검 필요")

합격률 80.0% → 점검 필요


## 7단계. 연습문제 — 온도·설비 이름으로 문장 만들기
**설명 포인트**: 1~2단계에서 배운 변수·f-string을 새로운 데이터로 한 번 더 반복 연습시키는
단계다. 운영안의 "빠른 학습자용 추가 과제"(온도·설비 변수를 조합한 문장 만들기)를 실제 노트북
실습으로 옮긴 것이므로, 빠른 학습자에게는 도전 문제까지, 느린 학습자에게는 앞의 두 셀(온도 저장,
평균 계산)까지만 요구해도 충분하다.

**예상 결과**: `EQ-02 온도: 23.5도, EQ-05 온도: 24.1도` → `두 설비의 평균 온도는 23.8도입니다.`
(두 번째 셀이 강의 자료 연습문제 "정답 보기"의 코드·실행 결과와 같다.)

In [14]:
# 두 설비의 온도를 각각 변수에 저장하고, 저장한 값을 문장으로 출력합니다.
# 실행하면 "EQ-02 온도: 23.5도, EQ-05 온도: 24.1도"가 출력됩니다.
temp_eq02 = 23.5
temp_eq05 = 24.1
print(f"EQ-02 온도: {temp_eq02}도, EQ-05 온도: {temp_eq05}도")

EQ-02 온도: 23.5도, EQ-05 온도: 24.1도


In [15]:
# 두 온도의 평균을 계산해 avg_temp에 저장하고, 소수 첫째 자리까지(:.1f) 출력합니다.
# 실행하면 "두 설비의 평균 온도는 23.8도입니다."가 출력됩니다.
avg_temp = (temp_eq02 + temp_eq05) / 2
print(f"두 설비의 평균 온도는 {avg_temp:.1f}도입니다.")

두 설비의 평균 온도는 23.8도입니다.


### 도전. 나만의 문장 만들기
**시연 방법**: 학생마다 문장 표현이 달라도 괜찮다는 점을 강조 — 정답은 하나가 아니다.

**예상 결과**(아래 예시 답안): `EQ-02: 온도 23.5도 · 습도 45.2%`, `EQ-05: 온도 24.1도 · 습도 44.8%`

In [16]:
# 두 설비의 습도를 각각 변수에 저장하고, 잘 저장됐는지 값을 출력해 확인합니다.
# 실행하면 45.2 44.8이 한 줄에 출력됩니다.
humidity_eq02 = 45.2
humidity_eq05 = 44.8
print(humidity_eq02, humidity_eq05)  # (중간 확인)

45.2 44.8


In [17]:
# 온도와 습도를 함께 담은 나만의 문장을 f-string으로 출력합니다.
# 실행하면 설비별로 온도와 습도가 들어간 문장이 출력됩니다(문장 표현은 사람마다 달라도 됩니다).
print(f"EQ-02: 온도 {temp_eq02:.1f}도 · 습도 {humidity_eq02:.1f}%")
print(f"EQ-05: 온도 {temp_eq05:.1f}도 · 습도 {humidity_eq05:.1f}%")

EQ-02: 온도 23.5도 · 습도 45.2%
EQ-05: 온도 24.1도 · 습도 44.8%


## 8단계. AI로 재미있는 미니 프로그램 만들기 🎉
**설명 포인트**: 과제 2(자기소개 카드)와는 다르게, 이 단계는 "AI에게 재미있는 아이디어를
제안받아 직접 실행해보는 경험" 자체가 목적이다. 정확한 코드보다 "AI와 대화하며 프로그램을
점점 재미있게 발전시키는 과정"을 즐기도록 유도한다.

프롬프트 예시: "input()으로 이름을 입력받고, 반도체 공정 운세 문장 리스트 중 하나를 무작위로
골라 이름과 함께 출력하는 파이썬 코드를 만들어줘."

**주의 안내**: `random.choice()`처럼 아직 배우지 않은 문법이 나올 수 있다 — 리스트(2차시)·
반복문(3차시)에서 다시 만날 표현이니 지금은 미리 구경하는 정도로 충분하다고 안내한다.

아래는 AI가 생성해줄 수 있는 예시 코드다(강의 자료 예시와 같은 코드, 자동 실행 검증에서는 `input()` 대신 예시 값을 대입).
강의 자료와 같게 `random.seed(42)`로 결과를 고정했으므로 몇 번을 실행해도 같은 운세가 나온다.
**seed 줄을 지우면(또는 앞에 `#`을 붙이면) 실행할 때마다 운세가 달라진다** — 무작위라는 점을 보여주고 싶으면
seed 줄을 지우고 두세 번 실행해 보인다.

**예상 결과**: `지민님의 오늘의 반도체 공정 운세: 오늘은 식각 공정에서 대박이 납니다!`

In [18]:
# AI가 만들어 줄 수 있는 "반도체 공정 운세 뽑기" 코드 예시입니다. 운세 문장 5개 중 하나를 무작위로 골라 이름과 함께 출력합니다.
# 실행하면 "지민님의 오늘의 반도체 공정 운세: 오늘은 식각 공정에서 대박이 납니다!"가 출력됩니다(seed 42로 고정).
# import random: 무작위 기능이 담긴 random 모듈을 불러옵니다. random.choice(리스트)는 리스트에서 하나를 무작위로 고릅니다.
# random.seed(숫자): 무작위 뽑기의 출발점을 정합니다. 같은 숫자를 쓰면 몇 번을 실행해도 같은 결과가 나옵니다.
import random

random.seed(42)  # 실행할 때마다 같은 결과가 나오도록 고정

name = "지민"  # 실제로는 input("이름을 입력하세요: ")
fortunes = [
    "오늘은 식각 공정에서 대박이 납니다!",
    "포토 공정에서 살짝 조심하세요.",
    "증착 공정 결과가 아주 좋을 예감입니다.",
    "세정을 꼼꼼히 하면 하루 종일 순조롭습니다.",
    "산화 공정에서 뜻밖의 좋은 소식이 있을 거예요.",
]

today_fortune = random.choice(fortunes)
print(f"{name}님의 오늘의 반도체 공정 운세: {today_fortune}")

지민님의 오늘의 반도체 공정 운세: 오늘은 식각 공정에서 대박이 납니다!
