# 9차시 강사용 Notebook — 머신러닝 예측 모델 만들기

**시연 전 안내**: Orange3로 File → Tree → Test and Score를 먼저 보여준 뒤 이 노트북으로 넘어갑니다.

## 1단계. 데이터 읽고 결측치 처리하기
**예상 결과**: 읽은 직후 `(750, 9)` → 열별 결측 개수(온도_섭씨 1 · 압력_Pa 3 · 가스유량_slm 3 · 습도_pct 8) → `dropna()` 후 `(735, 9)`.
**어려워할 부분**: scikit-learn 1.3 이상에서는 `dropna()` 셀을 건너뛰어도 오류가 나지 않는다. 오류를 기다리지 말고 마지막 `print(df.shape)`가 735를 찍는지로 확인시킨다(운영안 「실습 중 오류 대응」). 750이면 건너뛴 것이고, 이후 정확도·혼동행렬 수치가 강의 자료와 전부 어긋난다.

> ⚠️ **부호 규약 전환 — 9차시를 시작할 때 반드시 짚고 넘어간다.**
>
> 1~8차시의 `합격여부`는 `1`=합격, `-1`=불합격이었는데,
> 9·10차시의 `검사결과`는 **`0`=합격, `1`=불합격**이다 — 같은 `1`의 의미가 정반대로 뒤집힌다.
>
> **짚어주는 방법**: 2단계의 `y.value_counts()` 출력(0 → 582, 1 → 153)을 한 번 띄우고,
> "이 데이터에서 1은 불합격입니다"를 화면 한쪽에 적어둔 채로 수업을 시작한다.
> 4단계 정확도, 5단계 혼동행렬, 10차시 `불합격_확률`이 모두 이 약속 위에서 읽힌다는 점을 연결해준다.
>
> **학생이 자주 틀리는 지점**: 8차시 감각 그대로 `(y_test == 1).mean()`을 합격률로 쓰는 것 —
> 여기서는 그 값이 불합격률이다. 강의 슬라이드에도 `검사결과`(0=합격, 1=불합격)로 재고지돼 있으니
> 같은 표현으로 맞춰 읽어준다.

In [1]:
# 도구(pandas)를 불러오고, 오늘 사용할 CSV 파일을 읽어 df라는 표에 저장합니다.
# 실행하면 (행 개수, 열 개수)가 출력됩니다 — 결측치를 지우기 전의 원래 크기입니다.
import pandas as pd

df = pd.read_csv("../../data/weekly/week09/week09_pass_fail_train.csv")
print(df.shape)

(750, 9)


In [2]:
# 열마다 비어 있는 칸(결측값)이 몇 개인지 셉니다(5차시 복습).
# .isna(): 빈칸이면 True, 값이 있으면 False로 바꿉니다. 여기에 .sum()을 붙이면 열마다 True의 개수가 됩니다.
# 실행하면 열 이름과 결측 개수가 한 줄씩 보입니다 — 어느 열에 빈칸이 있는지 확인해 보세요.
print(df.isna().sum())

공정명          0
설비번호         0
온도_섭씨        1
압력_Pa        3
가스유량_slm     3
두께_nm        0
진공도_mTorr    0
습도_pct       8
검사결과         0
dtype: int64


In [3]:
# 결측값이 하나라도 있는 행을 지우고, 지운 뒤의 크기를 다시 확인합니다.
# 실행하면 (행 개수, 열 개수)가 출력됩니다 — 맨 위 셀의 행 개수보다 얼마나 줄었는지 비교해 보세요.
# 5차시 복습: 결측값이 있는 행 제거(이번에는 행 수가 충분해 제거해도 괜찮다)
df = df.dropna()
print(df.shape)

(735, 9)


## 2단계. Feature/Label 나누기
**설명 포인트**: 문자열 열(공정명, 설비번호)은 오늘 다루지 않는다는 것을 짚어준다.
**예상 결과**: `X.head()`는 숫자 열 6개만 보인다. `y.value_counts()`는 0(합격) 582건 · 1(불합격) 153건 — 합격이 약 79%인 불균형 데이터이고, 이것이 4단계 "기준선"의 근거가 된다.

In [4]:
# 예측에 쓸 입력 열(Feature, 특징) 6개의 이름을 feature_cols 목록에 담고, 그 열들만 골라 X에 저장합니다.
# 실행하면 X의 앞 5행이 보입니다 — 숫자 열 6개만 있고 공정명·설비번호·검사결과는 빠졌는지 확인해 보세요.
feature_cols = ["온도_섭씨", "압력_Pa", "가스유량_slm", "두께_nm", "진공도_mTorr", "습도_pct"]

X = df[feature_cols]   # Feature(특징)
X.head()  # (중간 확인)

,온도_섭씨,압력_Pa,가스유량_slm,두께_nm,진공도_mTorr,습도_pct
0,300.0,997.3,53.67,100.51,5.50,49.8
1,294.6,1018.2,50.88,95.48,4.61,42.7
2,299.6,996.3,51.55,98.23,5.46,53.8
3,307.2,1028.8,52.35,102.23,5.02,45.9
4,296.6,1017.8,50.85,95.13,5.04,43.5


In [5]:
# 맞히고 싶은 정답(Label)인 검사결과 열을 y에 저장합니다(0 = 합격, 1 = 불합격).
# 실행하면 0과 1이 각각 몇 건인지 보입니다 — 합격(0)이 훨씬 많은 "불균형 데이터"인지 확인해 보세요.
y = df["검사결과"]       # Label(정답)
y.value_counts()  # (중간 확인)

검사결과
0    582
1    153
Name: count, dtype: int64

## 3단계. train/test 분리 및 모델 학습
**예상 결과**: `(588, 6) (147, 6)`. 학습 셀은 학습을 마친 모델 설정 `DecisionTreeClassifier(max_depth=4, random_state=42)`를 표시한다.
**설명 포인트**: `stratify=y`를 빼면 불합격 사례가 적은 데이터에서 test에 불합격이 우연히 거의 들어가지 않게 나뉠 수 있다(운영안 「예상 오개념」). `DecisionTreeClassifier`는 3차시 if/elif/else처럼 "이 값이 이 기준보다 큰가?"를 반복하는 모델이다.

In [6]:
# 데이터를 학습용(train) 80%와 평가용(test) 20%로 나누고, 나뉜 두 덩어리의 크기를 확인합니다.
# 실행하면 (행, 열) 두 쌍이 출력됩니다 — 앞은 학습용 X_train, 뒤는 평가용 X_test의 크기입니다.
# 모델 도구 두 가지를 불러옵니다(DecisionTreeClassifier는 다음 셀에서 사용합니다).
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

# train_test_split: X와 y를 같은 규칙으로 섞은 뒤 X_train, X_test, y_train, y_test 네 덩어리로 나눠 줍니다.
# test_size=0.2: 20%를 평가용으로 / random_state=42: 매번 같은 방식으로 섞기 / stratify=y: 합격:불합격 비율 유지
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
print(X_train.shape, X_test.shape)

(588, 6) (147, 6)


In [7]:
# 나무 깊이(max_depth)가 4인 결정트리 모델을 만들고, 학습용 데이터(X_train, y_train)로 훈련시킵니다.
# 실행하면 DecisionTreeClassifier(max_depth=4, random_state=42)처럼 학습을 마친 모델의 설정이 표시됩니다.
model = DecisionTreeClassifier(max_depth=4, random_state=42)
# .fit(문제, 정답): 학습용 문제(X_train)와 정답(y_train)을 보고 규칙을 배웁니다.
model.fit(X_train, y_train)

,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.",'gini'
,"splitter splitter: {""best"", ""random""}, default=""best""The strategy used to choose the split at each node. Supportedstrategies are ""best"" to choose the best split and ""random"" to choosethe best random split.",'best'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",4
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: int, float or {""sqrt"", ""log2""}, default=NoneThe number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... note:: The search for a split does not stop until at least one valid partition of the node samples is found, even if it requires to effectively inspect more than ``max_features`` features.",None
,"random_state random_state: int, RandomState instance or None, default=NoneControls the randomness of the estimator. The features are alwaysrandomly permuted at each split, even if ``splitter`` is set to``""best""``. When ``max_features < n_features``, the algorithm willselect ``max_features`` at random at each split before finding the bestsplit among them. But the best found split may vary across differentruns, even if ``max_features=n_features``. That is the case, if theimprovement of the criterion is identical for several splits and onesplit has to be selected at random. To obtain a deterministic behaviourduring fitting, ``random_state`` has to be fixed to an integer.See :term:`Glossary ` for details.",42
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow a tree with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current no

## 4단계. 정확도 확인하기(그리고 기준선과 비교)
**가장 중요한 설명 포인트**: 모델 정확도(78.2%)가 기준선(78.9%)보다 낮다는 것을 직접 보여주며 '정확도의 함정'을 각인시킨다.
**예상 결과**: 예측 개수 0 → 134건, 1 → 13건 / `모델 정확도: 78.2%` / `기준선(무조건 합격 예측) 정확도: 78.9%`.

In [8]:
# 학습한 모델로 평가용 데이터(X_test)의 합격(0)/불합격(1)을 예측해 pred에 저장합니다.
# 실행하면 0과 1로 예측한 개수가 보입니다 — 147건 중 몇 건을 불합격(1)으로 예측했는지 확인해 보세요.
# 정확도 계산 도구(accuracy_score)를 불러옵니다(다음 셀에서 사용합니다).
from sklearn.metrics import accuracy_score

# .predict(문제): 학습한 규칙으로 새 문제의 답(0 또는 1)을 한꺼번에 예측합니다.
pred = model.predict(X_test)
# pd.Series(pred).value_counts(): 예측 결과를 표 한 줄로 바꾼 뒤 0과 1이 각각 몇 개인지 셉니다.
pd.Series(pred).value_counts()  # (중간 확인)

0    134
1     13
Name: count, dtype: int64

In [9]:
# 실제 정답(y_test)과 예측(pred)을 한 건씩 비교해 맞힌 비율(정확도)을 계산합니다.
# 실행하면 모델 정확도가 %로 출력됩니다.
# {값:.1%}: 0.782 같은 비율을 78.2%처럼 소수 첫째 자리 퍼센트로 보여 줍니다.
accuracy = accuracy_score(y_test, pred)
print(f"모델 정확도: {accuracy:.1%}")

모델 정확도: 78.2%


In [10]:
# 비교 기준(기준선)으로, 모든 로트를 "합격(0)"이라고만 찍었을 때의 정확도를 계산합니다.
# 실행하면 기준선 정확도가 출력됩니다 — 바로 위 셀의 모델 정확도와 어느 쪽이 높은지 비교해 보세요.
# (y_test == 0).mean(): 평가용 정답 중 0(합격)의 비율 = "무조건 합격"이라고 찍었을 때 맞히는 비율입니다.
# 비교 기준: "무조건 합격이라고만 예측"하면 정확도는 얼마일까?
baseline = (y_test == 0).mean()
print(f"기준선(무조건 합격 예측) 정확도: {baseline:.1%}")

기준선(무조건 합격 예측) 정확도: 78.9%


## 5단계. 혼동행렬 확인하기
**예상 결과**: `[[109   7]` / `[ 25   6]]` — 실제 불합격 31건(25+6) 중 모델이 맞힌 것은 6건뿐(약 19%)이고, 25건은 불합격을 합격으로 놓친 경우(FN, 놓친 불량)다.
**설명 포인트**: 오른쪽 열의 합 7 + 6 = 13이 4단계에서 모델이 불합격(1)으로 예측한 개수다. "정확도는 기준선보다 낮지만 그래도 불합격 6건을 찾아냈다"는 균형 잡힌 해석을 함께 제시한다.

In [11]:
# 혼동행렬: 실제 정답과 예측을 조합별로 세어 2×2 표로 보여 줍니다.
# 실행하면 숫자 4개가 출력됩니다 — 윗줄은 실제 합격(0), 아랫줄은 실제 불합격(1) / 왼쪽 칸은 합격 예측, 오른쪽 칸은 불합격 예측입니다.
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, pred)
print(cm)

[[109   7]
 [ 25   6]]


## 6단계(종합). 중요 특징 확인하기
**예상 결과**: 온도_섭씨 51.7% · 압력_Pa 2.6% · 가스유량_slm 10.7% · 두께_nm 9.8% · 진공도_mTorr 20.8% · 습도_pct 4.4%.
**설명 포인트**: 8차시와 연결하되 **무엇의 원인 후보였는지** 정확히 짚는다. 8차시에서 불합격의 원인 후보로 남은 것은 진공도 이탈이었고, 온도는 두께의 원인 후보였을 뿐 불합격의 원인 후보가 아니었다. 중요도 순위를 8차시 결과와 뭉뚱그려 "일치한다"고 말하지 않는다. 중요도는 "모델이 많이 참고한 값"일 뿐이라 원인 후보를 좁히는 참고 자료로만 쓴다 — "예측이 잘 된다"와 "원인을 증명한다"는 다른 말이다.

In [12]:
# 모델이 예측할 때 각 특징(열)을 얼마나 많이 참고했는지(중요도)를 %로 출력합니다.
# 실행하면 특징 6개의 중요도가 한 줄씩 보입니다 — 중요도는 "모델이 많이 참고한 값"일 뿐 원인이 확정된 것이 아니므로, 원인 후보를 좁히는 참고 자료로만 씁니다.
# zip(A, B): 두 목록에서 같은 순서의 값을 하나씩 짝지어 꺼내 줍니다. model.feature_importances_는 학습된 모델이 계산한 특징별 중요도입니다.
for name, importance in zip(feature_cols, model.feature_importances_):
    print(f"{name}: {importance:.1%}")

온도_섭씨: 51.7%
압력_Pa: 2.6%
가스유량_slm: 10.7%
두께_nm: 9.8%
진공도_mTorr: 20.8%
습도_pct: 4.4%


## 7단계. 오늘의 학습을 한 문장으로 정리하기
**진행 방법**: "정확도가 몇 %였나"가 아니라 "그 정확도를 믿어도 되나"를 묻는다. 4단계의 기준선과 5단계의 혼동행렬을 함께 언급하는 문장이 나오면 성공이다.
**설명 포인트**: 결과 해석 문장 쓰기는 1차시부터 10차시까지 매 차시 빠지지 않는 고정 활동이다(docs/curriculum.md 「차시 간 연결 원칙」). 코드를 친 것으로 끝내지 않고 자기 말로 바꿔 말해보게 하는 것이 이 과정의 목표 — "데이터로 공정 상태를 설명할 수 있는 사람" — 에 직접 닿는 활동이므로 시간이 모자라도 2~3분은 반드시 확보한다.

> (예시 답안) 정확도만 보면 모델이 괜찮아 보이지만, 혼동행렬을 보면 불합격을 잘 못 잡아낸다는 것을 알 수 있다. 불균형 데이터에서는 정확도만으로 판단하면 안 된다.

### 도전 문제 1 — max_depth를 바꿔 train/test 정확도와 혼동행렬 비교하기 (빠른 학습자용)

강의 「도전 실습」의 도전 문제입니다. 10단계 연습문제에서 쓰는 깊이(2, 8) 외에 3, 6, 10까지 바꿔 가며, 깊이마다 ① train 정확도와 test 정확도 ② 혼동행렬을 비교합니다. 어떤 깊이가 가장 균형 잡힌 결과를 주는지 찾아보세요. 1~7단계를 마친 뒤 시간이 남으면 풀어 봅니다.

**세 노트북 공통 셀**(1차의 강사용 전용 "확장 실습" 셀을 전환) — 학생용은 강의 본문에 나온 토큰만 빈칸으로 가리고, 빈칸 셀마다 바로 뒤에 참고 셀이 있다.
**설명 포인트**: 강의 「도전 실습」 체크포인트 — `max_depth`를 키우면 train 정확도는 거의 항상 오르므로, 진짜 실력은 test 정확도로 확인한다. 두 값의 차이가 벌어지면 과대적합(overfitting) 신호다. 예상 결과는 각 참고 셀에 실제 실행값으로 적었다.

In [13]:
# (도전 문제 1-①) 나무 깊이(max_depth)를 2, 3, 4, 6, 8, 10으로 바꿔 가며 모델을 새로 학습시키고, 깊이마다 train 정확도와 test 정확도를 한 줄씩 출력합니다.
# 실행하면 여섯 줄이 출력됩니다 — 깊이가 커질수록 두 정확도가 각각 어떻게 움직이는지, 둘의 차이가 벌어지는지 보세요.
# 4단계에서 만든 model은 11단계에서 다시 쓰므로, 여기서는 새 모델의 이름을 m으로 따로 둡니다(model을 덮어쓰지 않기 위해).
depths = [2, 3, 4, 6, 8, 10]
for depth in depths:
    m = DecisionTreeClassifier(max_depth=depth, random_state=42)
    m.fit(X_train, y_train)
    # 학습에 쓴 데이터(X_train, y_train)로 잰 정확도와, 처음 보는 평가용 데이터(X_test, y_test)로 잰 정확도를 따로 구합니다.
    train_acc = m.score(X_train, y_train)
    test_acc = m.score(X_test, y_test)
    print(f"max_depth={depth}: train 정확도 {train_acc:.1%}, test 정확도 {test_acc:.1%}")

max_depth=2: train 정확도 81.5%, test 정확도 78.9%
max_depth=3: train 정확도 83.7%, test 정확도 79.6%
max_depth=4: train 정확도 85.5%, test 정확도 78.2%
max_depth=6: train 정확도 93.2%, test 정확도 74.8%
max_depth=8: train 정확도 95.7%, test 정확도 75.5%
max_depth=10: train 정확도 97.3%, test 정확도 73.5%


> **참고**
>
> - 빈칸(두 곳, 같은 이름): 강의 「도전 실습」의 **체크포인트 — train 정확도만 보면 착각하기 쉽다** 상자를 다시 보세요. 학습에 쓴 데이터로 잰 정확도와 평가용 데이터로 잰 정확도를 구하는 코드가 그대로 나옵니다. 이 메서드는 모델에 문제(X)와 정답(y)을 함께 넘기면 스스로 예측한 뒤 정답과 비교해 맞힌 비율(0~1)을 돌려줍니다 — 4단계에서 예측하기와 정확도 계산하기를 두 줄로 나눠 한 일을 한 번에 하는 셈입니다.
> - 결과 읽기: 같은 상자에 train 정확도와 test 정확도의 차이가 크게 벌어지면 무엇의 신호인지도 적혀 있습니다.
>
> **정답 해설:** 두 빈칸 모두 `score`다. `m.score(X_train, y_train)`은 이미 본 문제로 잰 점수라 깊이가 커질수록 계속 오르고, `m.score(X_test, y_test)`는 처음 보는 문제로 잰 점수라 진짜 실력은 이쪽으로 판단한다.
>
> **예상 결과(실제 실행값):** max_depth=2 → train 81.5% / test 78.9%, 3 → 83.7% / 79.6%, 4 → 85.5% / 78.2%, 6 → 93.2% / 74.8%, 8 → 95.7% / 75.5%, 10 → 97.3% / 73.5%. train은 깊이와 함께 계속 오르지만 test는 max_depth=3에서 79.6%로 가장 높고 그 뒤로 내려가, max_depth=10에서 차이가 가장 크게 벌어진다(과대적합 신호). 이 데이터·이 분할에서 관찰된 경향일 뿐이다.

In [14]:
# (도전 문제 1-②) 같은 깊이들로 모델을 다시 학습시켜, 깊이마다 평가용 데이터(X_test)에 대한 혼동행렬을 출력합니다.
# 실행하면 깊이마다 "max_depth=숫자" 줄과 2×2 표가 하나씩 보입니다 — 아랫줄 오른쪽 칸(불합격을 맞힌 수)과 윗줄 오른쪽 칸(합격을 불합격으로 잘못 잡은 수)이 어떻게 바뀌는지 보세요.
for depth in depths:
    m = DecisionTreeClassifier(max_depth=depth, random_state=42)
    m.fit(X_train, y_train)
    print(f"max_depth={depth}")
    print(confusion_matrix(y_test, m.predict(X_test)))

max_depth=2
[[113   3]
 [ 28   3]]
max_depth=3
[[112   4]
 [ 26   5]]
max_depth=4
[[109   7]
 [ 25   6]]
max_depth=6
[[105  11]
 [ 26   5]]
max_depth=8
[[105  11]
 [ 25   6]]
max_depth=10
[[102  14]
 [ 25   6]]


> **참고**
>
> - 빈칸: 강의 「정확도 확인하기 — 그리고 정확도의 함정」 절의 **혼동행렬(Confusion Matrix)로 자세히 보기** 코드 블록을 다시 보세요(노트북 5단계와 같은 코드). 실제 정답과 예측을 차례로 넣으면 합격·불합격 조합별 개수를 2×2 표로 세어 주는 함수입니다. 여기서는 5단계의 `pred` 대신 이 깊이 모델의 예측 `m.predict(X_test)`를 넣습니다.
> - 결과 읽기: 표 읽는 법은 같은 절의 표(실제 합격/불합격 × 예측 합격/불합격)를 보세요. "가장 균형 잡힌 결과"는 test 정확도 하나가 아니라, 불합격을 맞힌 수(아랫줄 오른쪽)와 합격을 불합격으로 잘못 잡은 수(윗줄 오른쪽)를 함께 보고 판단합니다.
>
> **정답 해설:** 빈칸은 `confusion_matrix`다. 5단계에서 쓴 함수를 그대로 쓰되, 깊이마다 새로 학습한 모델 `m`의 예측을 넣어 깊이별 오류의 종류를 비교한다.
>
> **예상 결과(실제 실행값):** max_depth=2 → `[[113 3] [28 3]]`, 3 → `[[112 4] [26 5]]`, 4 → `[[109 7] [25 6]]`, 6 → `[[105 11] [26 5]]`, 8 → `[[105 11] [25 6]]`, 10 → `[[102 14] [25 6]]`.
>
> **설명 포인트:** max_depth=4 이상에서는 불합격을 맞힌 수가 5~6건에 머물고, 합격을 불합격으로 잘못 잡은 수만 7건(4)→11건(6·8)→14건(10)으로 늘어난다. max_depth=3은 test 정확도가 가장 높지만(79.6%) 불합격은 5건만 맞힌다. "가장 균형 잡힌 값"은 놓친 불량과 잘못 잡은 합격 중 무엇을 더 중요하게 보느냐에 따라 달라질 수 있으므로 정답 하나로 몰지 말고 근거를 말하게 한다. max_depth=2의 78.9%는 기준선과 우연히 같은 값이고, 실제로는 불합격을 6건(3+3) 예측했다.

## 오류 대처 방법
- `ValueError: could not convert string to float` 발생 시: Feature에 문자열 열(공정명, 설비번호)이 섞였는지 확인.
- `KeyError: '검사 결과'`처럼 `KeyError`가 나면: 열 이름 오타(띄어쓰기 포함)다. `df.columns`로 실제 열 이름(`검사결과`)을 확인한다(직접 실행해 확인한 오류).
- 정확도가 비정상적으로 높으면(거의 100%): Feature에 검사결과가 실수로 포함됐는지 확인.
- `dropna()` 셀을 건너뛰어도 오류가 나지 않는다(scikit-learn 1.3 이상) — 1단계 `print(df.shape)`가 735인지로 확인.
- 도전 문제 1에서 모델 이름을 `m` 대신 `model`로 바꿔 쓰면 4단계 모델(max_depth=4)이 max_depth=10 모델로 바뀐 채 11단계 미니 데모가 실행된다. 강의 sample 값은 두 모델 모두 합격으로 같지만(직접 확인), sample 값을 바꿔 실험하면 강의 모델과 다른 예측이 나올 수 있다. 셀 안 이름은 `m` 그대로 두게 한다.

## 8단계. AI에게 질문하며 더 알아보기
**설명 포인트**: 불균형 데이터 대응법 질문이 나오면, 오늘 이미 확인한 "정확도의 함정"과
연결해 왜 다른 지표/방법이 필요한지 강조한다.

질문 예시:
- "결정트리 말고 다른 분류 모델에는 어떤 것들이 있나요? (로지스틱 회귀, 랜덤 포레스트 등)"
- "정확도(accuracy) 말고 모델 성능을 평가하는 다른 지표(정밀도, 재현율, F1)는 각각 무엇을 의미하나요?"
- "max_depth를 너무 깊게 설정하면 어떤 문제(과대적합)가 생기나요?"
- "오늘처럼 합격이 압도적으로 많은 불균형 데이터를 다루는 다른 방법들이 있나요?"

## 9단계. AI에게 코드 생성 요청하고 직접 실행해보기
**설명 포인트**: `precision_score`, `recall_score`는 오늘 배우지 않은 함수다 — 혼동행렬의
네 칸(TP/FP/FN/TN)과 정밀도·재현율의 관계를 그림으로 짚어주면 이해가 빠르다.

프롬프트 예시: "실제값과 예측값 리스트를 받아서, 정확도·정밀도·재현율을 한 번에 출력하는
코드를 만들어줘."

아래는 AI가 생성해줄 수 있는 예시 코드와 실행 결과다(강의와 같은 코드). **예상 결과**: `정확도: 0.67` / `정밀도: 0.67` / `재현율: 0.67` — 연습용 6개 목록으로 계산한 값이다. 같은 함수를 오늘 모델(`y_test`, `pred`)에 쓰면 정밀도 0.46(불합격 예측 13건 중 6건 적중)·재현율 0.19(실제 불합격 31건 중 6건)로, 5단계 혼동행렬의 "약 19%"와 같은 값이라는 점을 연결해준다.

In [15]:
# AI가 만들어 줄 수 있는 코드 예시입니다. 실제값(y_true) 6개와 예측값(y_pred) 6개로 정확도·정밀도·재현율을 계산합니다.
# 실행하면 세 지표가 한 줄씩 출력됩니다 — 오늘 모델이 아니라 연습용 작은 목록으로 계산한 값입니다.
# 정밀도(precision): 불합격(1)이라고 예측한 것 중 실제 불합격의 비율 / 재현율(recall): 실제 불합격 중 모델이 찾아낸 비율
from sklearn.metrics import precision_score, recall_score, accuracy_score

y_true = [0, 0, 0, 1, 1, 1]
y_pred = [0, 0, 1, 1, 1, 0]

print(f"정확도: {accuracy_score(y_true, y_pred):.2f}")
print(f"정밀도: {precision_score(y_true, y_pred):.2f}")
print(f"재현율: {recall_score(y_true, y_pred):.2f}")

정확도: 0.67
정밀도: 0.67
재현율: 0.67


## 10단계. 연습문제 — 나무 깊이(max_depth) 바꿔보기
**설명 포인트**: `max_depth`가 작으면(2) 나무가 단순해 학습 데이터의 패턴도 충분히 못 잡을 수
있고(과소적합, underfitting), 너무 크면(8) 학습 데이터에 지나치게 맞춰져 새로운 데이터에서는
오히려 성능이 떨어질 수 있다(과대적합, overfitting)는 트레이드오프를 짚어준다. 아래 결과는
이 데이터·이 depth 값에서 실제로 관찰된 경향일 뿐 — depth나 데이터가 달라지면 순서가 바뀔 수도
있으므로 "depth가 크면 무조건 나쁘다"처럼 단정하지 않도록 주의한다.
**예상 결과**: `max_depth=2 정확도: 78.9%` / `max_depth=8 정확도: 75.5%`. 78.9%는 "모두 합격" 기준선과 우연히 같은 값이고 실제로는 불합격을 6건 예측했다. 깊은 나무(8)의 train 정확도 95.7%는 7단계 "도전 문제 1" 셀(세 노트북 공통)에서 보여줄 수 있다.

In [16]:
# 나무 깊이를 2로 줄인(얕은) 결정트리를 새로 학습시키고, 평가용 데이터로 정확도를 계산해 acc_shallow에 저장합니다.
# 이 셀은 계산만 하고 출력은 없습니다 — 결과는 두 셀 아래에서 max_depth=8과 함께 비교합니다.
model_shallow = DecisionTreeClassifier(max_depth=2, random_state=42)
model_shallow.fit(X_train, y_train)
acc_shallow = accuracy_score(y_test, model_shallow.predict(X_test))

In [17]:
# 이번에는 나무 깊이를 8로 늘린(깊은) 결정트리를 학습시키고, 정확도를 acc_deep에 저장합니다.
# 이 셀도 계산만 하고 출력은 없습니다 — 바로 다음 셀에서 두 정확도를 함께 출력합니다.
model_deep = DecisionTreeClassifier(max_depth=8, random_state=42)
model_deep.fit(X_train, y_train)
acc_deep = accuracy_score(y_test, model_deep.predict(X_test))

In [18]:
# 두 모델의 test 정확도를 나란히 출력합니다.
# 실행하면 두 줄이 보입니다 — 4단계의 max_depth=4 정확도(78.2%)와 비교해, 깊을수록 항상 좋아지는지 확인해 보세요.
print(f"max_depth=2 정확도: {acc_shallow:.1%}")
print(f"max_depth=8 정확도: {acc_deep:.1%}")

max_depth=2 정확도: 78.9%
max_depth=8 정확도: 75.5%


## 11단계. AI로 재미있는 미니 프로그램 만들기 🎉 — 합격 예측 미니 데모
**설명 포인트**: 이미 학습된 `model`과 `feature_cols`를 그대로 재사용한다는 점을 강조한다 —
모델을 다시 학습시키지 않고도 새로운 값 하나만으로 바로 예측해볼 수 있다는 것이 오늘 만든
모델의 실용적인 쓰임새다. `검사결과`는 0=합격, 1=불합격으로 인코딩되어 있으므로
`if result == 0:` 분기가 핵심이다. 이 노트북은 자동 실행 검증 대상이라 `input()` 대신 고정된
샘플 값을 사용한다.

프롬프트 예시: "학습된 분류 모델(model)과 특징 이름 리스트(feature_cols)가 있을 때, 새로운 값
하나를 입력받아 데이터프레임 한 행으로 만들고 model.predict()로 합격/불합격을 재미있게
알려주는 파이썬 코드를 만들어줘."

아래는 AI가 생성해줄 수 있는 예시 코드다(강의와 같은 코드). **예상 결과**: `result`가 0이라 합격 문구가 출력된다.

In [19]:
# AI가 만들어 줄 수 있는 "합격 예측 미니 데모" 코드 예시입니다. 공정 조건 한 세트를 표 한 행(sample)으로 만들어 모델에 넣습니다.
# 실행하면 모델의 예측에 따라 합격 문구 또는 불합격 위험 문구가 한 줄 출력됩니다 — sample의 숫자를 바꿔 다시 실행해 보세요.
# pd.DataFrame([{열 이름: 값, ...}]): 딕셔너리 하나를 행 하나짜리 표로 만듭니다. model.predict(...)[0]은 예측 결과 중 첫 번째(유일한) 값입니다.
sample = pd.DataFrame([{
    "온도_섭씨": 301.5, "압력_Pa": 1010.0, "가스유량_slm": 52.0,
    "두께_nm": 100.5, "진공도_mTorr": 5.0, "습도_pct": 45.0,
}])  # 실제로는 input()으로 각 값을 하나씩 입력받아도 좋다.

result = model.predict(sample[feature_cols])[0]
if result == 0:
    print("🎉 합격일 것 같아요!")
else:
    print("⚠️ 불합격 위험이 있어요, 공정을 다시 확인해보세요.")

🎉 합격일 것 같아요!
